# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987b964f4938b8ae319524ff0882d5063b01b33bb80ae04e53543411b40369f0641f5e74453b5d5e715ee019df80decebd0509d96546a49ee8d1efd0a64b7630

test:
  secret_key_base: 6e1dd47af6fa550b7184c77d0e80af51df35f82140d3fb199d4b3ad6d1000512747f8ac41f8dbe1cdc654cada307188670b20ba4c2075642279e416a3e4dd1e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
